---
title: "new-class-enrollment"
author: "Vivian Zhang"
date: "3/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(utils)
library(janitor)
library(tidyverse)

```

```{r download files, include=FALSE}
url_currect <- "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_2.25.20_0.xlsx"

url_old <- "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_3.22.19_0.xlsx"

download.file(url = url_currect, destfile = "current.xlsx")

download.file(url = url_old, destfile = "old.xlsx")

current <- read_excel("current.xlsx", skip=3) %>%
  clean_names() %>%
  filter(! is.na(course_name))

old <- read_excel("old.xlsx", skip=3) %>%
  clean_names() %>%
  filter(! is.na(course_name))

# Five biggest new courses this semester
```

```{r readxl, echo=FALSE}

new_courses <- current %>%
  anti_join(old, by="course_id") %>%
  arrange(desc(total)) %>%
  slice(1:5) %>%
  pull(course_name)
new_courses

```


